# Name of workflow
name: Development

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Install packages
      - name: Install node packages
      - run: yarn
      # Run npm install and build on our code
      - name: Generate Site
      - run: yarn generate
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
      - run: npx netlify deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
      